# Use postgres/example user/password credentials
version: '3.1'

networks:
  app-tier:
    driver: bridge

services:

  db:
    image: bitnami/postgresql:16
    restart: always
    environment:
      ##PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres    
    volumes:
      ##- ~/databases/postgresql-data:/var/lib/postgresql/data
      ##- ~/Databases/postgresql-conf:/bitnami/postgresql/conf
      - ~/Databases/postgresql-data:/bitnami/postgresql
    ports:
      - 5432:5432
    networks:
      - app-tier

  pgadmin4:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - ~/Databases/postgresql-pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
    networks:
      - app-tier    
